### ISSUE TITLE
Trouble error: loading audio

### ISSUE THREAD

**Issue by NAVIuserWired** [UnderMybrella/EternalJukebox#27] opened 2018-01-22 17:26 UTC
### Description
Having trouble loading about half the songs I try. On Firefox I get the error:  "Sorry, can't find info for that track" for absolutely every song. In Chrome some songs load but most of them I have tried says that it is fetching, loading, and then "Trouble error: loading audio"

### Song
https://eternal.abimon.org/canonizer_go.html?id=0T6oJ6A8MCSyl6EXqdatKm
https://eternal.abimon.org/canonizer_go.html?id=3fLeBPjggYrZLSi6WFZRh5
https://eternal.abimon.org/canonizer_go.html?id=5uORXVBCCN45rbW5LOuurt

### Additional Information
None

**Comment by itsrajivshah** [comment] 2018-02-13 21:08
I can confirm that this is happening on [this song.](https://github.com/UnderMybrella/EternalJukebox/issues/27)

In the console on Chrome, it throws an audio error `audio error DOMException: Unable to decode audio data` and this is mirrored in Firefox, where I get this message `The buffer passed to decodeAudioData contains an unknown content type.` and `Error: Unauthorized
jukebox_go.html:1526:21`.

This behavior occurs both with default audio sources and uploaded MP3's.

**Comment by UnderMybrella** [comment] 2018-02-15 12:12
The live server has an issue right now where audio files don't get properly uploaded or marked as public. While this *is* a bug, I've fixed it by rewriting the central storage processing in the rewrite branch.

I'm leaving this open until the patches get merged, which should be soon.

**Comment by itsrajivshah** [comment] 2018-02-18 16:07
Cheers - I can confirm that it is now working for me on the rewrite branch

**Closed** 2018-03-25 15:58 UTC
Labels: bug, fixed

**Comment by SmallJoker** [comment] 2019-09-09 17:11
Please re-open this issue, it's happening again.
```
Unknown property '    -moz-border-radius'.  Declaration dropped. styles.css:53:24
Unknown property 'wdith'.  Declaration dropped. styles.css:77:11
The resource at “<URL>” was blocked because content blocking is enabled. 4
Could not retrieve stars: Unauthorized jukebox_go.html:1329:29
XML Parsing Error: syntax error
Location: https://eternalbox.dev/api/profile/me
Line Number 1, Column 1: me:1:1
audio error DOMException: "MediaDecodeAudioDataUnknownContentType" jremix.js:39:41
The buffer passed to decodeAudioData contains an unknown content type. jukebox_go.html
EncodingError: The given encoding is not supported.
```
Feels like any result of "alan parsons instrumental" is affected, in case you'd like to try.
Tested several times using:
- Firefox 69.0
- No extensions/addons
- https://eternalbox.dev/jukebox_go.html?id=6TErrSCoOBfHFeju90jgoJ

**Comment by SmallJoker** [comment] 2019-09-13 17:59
<3 Thank so much

**Comment by mnemocron** [comment] 2021-07-07 18:49
I have the same error but I am not sure it it is related to this issue as it is due to a 400 bad request.

It happens with 100% of the songs, I have not yet successfully played anything.


```
XHRGEThttp://192.168.1.7:12121/api/audio/jukebox/7AHaKrKuhzpl4xK0r2Jd9g
[HTTP/1.1 400 Bad Request 63ms]

	
GET
	http://192.168.1.7:12121/api/audio/jukebox/7AHaKrKuhzpl4xK0r2Jd9g
Status400
Bad Request
VersionHTTP/1.1
Transferred209 B (77 B size)
Referrer Policystrict-origin-when-cross-origin

    	
    content-length
    	77
    Content-Type
    	application/json
    X-Client-UID
    	9773d116-f052-473e-b2c5-4788f031e206
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Cookie
    	__utma=91153882.809449416.1625683189.1625683189.1625683189.1; __utmb=91153882.10.10.1625683189; __utmc=91153882; __utmz=91153882.1625683189.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmt=1
    DNT
    	1
    Host
    	192.168.1.7:12121
    Referer
    	http://192.168.1.7:12121/canonizer_go.html?id=7AHaKrKuhzpl4xK0r2Jd9g
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
```

**Comment by dennorske** [comment] 2021-07-11 18:51
I am getting the same issues; 
![image](https://user-images.githubusercontent.com/3287543/125206879-ab768400-e289-11eb-853a-b016a192a15e.png)

Unsure what is causing it. I tried both Chrome and Firefox.

**Comment by KonkenBonken** [comment] 2023-08-12 20:39
I still get this error
![image](https://github.com/UnderMybrella/EternalJukebox/assets/49250602/f146329b-56e1-470a-94ca-36af9249a0fa)

With the HTTP GET request to `https://www.eternalboxmirror.xyz/api/audio/jukebox/[id]` giving a response 400:
```json
{
  "error":  "Audio is null",
  "client_uid":  "620000be-c008-4006-900b-b00000000005"
}
```
